### ISSUE TITLE
`create exact synonym` from the GitHub issue somehow gets parsed as `createexactsynonym` in kgcl-java.

### ISSUE THREAD

**Issue by hrshdhgd** [gouttegd/kgcl-java#5]
Error:
```bash
2024-08-28 18:15:50,063 ERROR org.incenp.obofoundry.kgcl.robot.ApplyCommand - KGCL syntax error: line 1, column 45: no viable alternative at input 'createexactsynonym'ocean basin floor'for'ocean floor''
```

Issue that highlighted the error: https://github.com/EnvironmentOntology/envo/issues/1518

GH Action: https://github.com/EnvironmentOntology/envo/actions/runs/10602157613/job/29383593707 

kgcl-java version: 0.3.2 (need to update and have a PR for ENVO ready)

@gouttegd : are the single quotes in the command messing up something?

**Comment by gouttegd** [comment]
The error message from the parser is somewhat misleading (I’ll see if I can make it more useful), but this has nothing to do with `create exact synonym` being somehow parsed as `createexactsynonym`.

The problem is with the `for 'ocean floor'`. The parser expects a term ID after `for`, _not_ a string. KGCL-Java does not support using a _label_ where an _ID_ is expected. This is on purpose: you want to modify a term, you are supposed to know its ID; KGCL-Java will not do the lookup for you.

So here, the command should have been

```
create exact synonym 'ocean basin floor' for ENVO:00000426
```

**Comment by hrshdhgd** [comment]
Thank you for the quick response @gouttegd !

**Comment by cmungall** [comment]
Can be closed, but we should continue discussion about labels here: https://github.com/INCATools/kgcl/issues/82
